// Generated by gencpp from file vehicle_manager/DeleteVehicle.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_DELETEVEHICLE_H
#define VEHICLE_MANAGER_MESSAGE_DELETEVEHICLE_H

#include <ros/service_traits.h>


#include <vehicle_manager/DeleteVehicleRequest.h>
#include <vehicle_manager/DeleteVehicleResponse.h>


namespace vehicle_manager
{

struct DeleteVehicle
{

typedef DeleteVehicleRequest Request;
typedef DeleteVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteVehicle
} // namespace vehicle_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vehicle_manager::DeleteVehicle > {
  static const char* value()
  {
    return "26021b5c78adc94a5ca3e835030134b8";
  }

  static const char* value(const ::vehicle_manager::DeleteVehicle&) { return value(); }
};

template<>
struct DataType< ::vehicle_manager::DeleteVehicle > {
  static const char* value()
  {
    return "vehicle_manager/DeleteVehicle";
  }

  static const char* value(const ::vehicle_manager::DeleteVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::vehicle_manager::DeleteVehicleRequest> should match
// service_traits::MD5Sum< ::vehicle_manager::DeleteVehicle >
template<>
struct MD5Sum< ::vehicle_manager::DeleteVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::DeleteVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DeleteVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::DeleteVehicleRequest> should match
// service_traits::DataType< ::vehicle_manager::DeleteVehicle >
template<>
struct DataType< ::vehicle_manager::DeleteVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::DeleteVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DeleteVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vehicle_manager::DeleteVehicleResponse> should match
// service_traits::MD5Sum< ::vehicle_manager::DeleteVehicle >
template<>
struct MD5Sum< ::vehicle_manager::DeleteVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::DeleteVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DeleteVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::DeleteVehicleResponse> should match
// service_traits::DataType< ::vehicle_manager::DeleteVehicle >
template<>
struct DataType< ::vehicle_manager::DeleteVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::DeleteVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DeleteVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_DELETEVEHICLE_H
