// Generated by gencpp from file vehicle_manager/DisplayAllVehicleRequest.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLEREQUEST_H
#define VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_manager
{
template <class ContainerAllocator>
struct DisplayAllVehicleRequest_
{
  typedef DisplayAllVehicleRequest_<ContainerAllocator> Type;

  DisplayAllVehicleRequest_()
    {
    }
  DisplayAllVehicleRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DisplayAllVehicleRequest_

typedef ::vehicle_manager::DisplayAllVehicleRequest_<std::allocator<void> > DisplayAllVehicleRequest;

typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleRequest > DisplayAllVehicleRequestPtr;
typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleRequest const> DisplayAllVehicleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vehicle_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_manager/DisplayAllVehicleRequest";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DisplayAllVehicleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vehicle_manager::DisplayAllVehicleRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLEREQUEST_H
