// Generated by gencpp from file vehicle_manager/DisplayAllVehicle.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLE_H
#define VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLE_H

#include <ros/service_traits.h>


#include <vehicle_manager/DisplayAllVehicleRequest.h>
#include <vehicle_manager/DisplayAllVehicleResponse.h>


namespace vehicle_manager
{

struct DisplayAllVehicle
{

typedef DisplayAllVehicleRequest Request;
typedef DisplayAllVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisplayAllVehicle
} // namespace vehicle_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vehicle_manager::DisplayAllVehicle > {
  static const char* value()
  {
    return "7972a9cea7f1344cbb3d6fe3b301435d";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicle&) { return value(); }
};

template<>
struct DataType< ::vehicle_manager::DisplayAllVehicle > {
  static const char* value()
  {
    return "vehicle_manager/DisplayAllVehicle";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::vehicle_manager::DisplayAllVehicleRequest> should match
// service_traits::MD5Sum< ::vehicle_manager::DisplayAllVehicle >
template<>
struct MD5Sum< ::vehicle_manager::DisplayAllVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::DisplayAllVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DisplayAllVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::DisplayAllVehicleRequest> should match
// service_traits::DataType< ::vehicle_manager::DisplayAllVehicle >
template<>
struct DataType< ::vehicle_manager::DisplayAllVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::DisplayAllVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DisplayAllVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vehicle_manager::DisplayAllVehicleResponse> should match
// service_traits::MD5Sum< ::vehicle_manager::DisplayAllVehicle >
template<>
struct MD5Sum< ::vehicle_manager::DisplayAllVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::DisplayAllVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DisplayAllVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::DisplayAllVehicleResponse> should match
// service_traits::DataType< ::vehicle_manager::DisplayAllVehicle >
template<>
struct DataType< ::vehicle_manager::DisplayAllVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::DisplayAllVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::DisplayAllVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLE_H
