// Generated by gencpp from file vehicle_manager/DisplayAllVehicleResponse.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLERESPONSE_H
#define VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vehicle_manager/Vehicle.h>

namespace vehicle_manager
{
template <class ContainerAllocator>
struct DisplayAllVehicleResponse_
{
  typedef DisplayAllVehicleResponse_<ContainerAllocator> Type;

  DisplayAllVehicleResponse_()
    : success(false)
    , message()
    , vehicles()  {
    }
  DisplayAllVehicleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , vehicles(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::vehicle_manager::Vehicle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vehicle_manager::Vehicle_<ContainerAllocator> >> _vehicles_type;
  _vehicles_type vehicles;





  typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DisplayAllVehicleResponse_

typedef ::vehicle_manager::DisplayAllVehicleResponse_<std::allocator<void> > DisplayAllVehicleResponse;

typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleResponse > DisplayAllVehicleResponsePtr;
typedef boost::shared_ptr< ::vehicle_manager::DisplayAllVehicleResponse const> DisplayAllVehicleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator1> & lhs, const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.vehicles == rhs.vehicles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator1> & lhs, const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7972a9cea7f1344cbb3d6fe3b301435d";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7972a9cea7f1344cULL;
  static const uint64_t static_value2 = 0xbb3d6fe3b301435dULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_manager/DisplayAllVehicleResponse";
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"Vehicle[] vehicles\n"
"\n"
"================================================================================\n"
"MSG: vehicle_manager/Vehicle\n"
"uint32 id\n"
"string licensePlate\n"
"string make\n"
"string model\n"
"string year\n"
;
  }

  static const char* value(const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.vehicles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DisplayAllVehicleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_manager::DisplayAllVehicleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vehicles: ";
    if (v.vehicles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.vehicles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::vehicle_manager::Vehicle_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.vehicles[i]);
    }
    if (v.vehicles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_DISPLAYALLVEHICLERESPONSE_H
