// Generated by gencpp from file vehicle_manager/EditVehicle.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_EDITVEHICLE_H
#define VEHICLE_MANAGER_MESSAGE_EDITVEHICLE_H

#include <ros/service_traits.h>


#include <vehicle_manager/EditVehicleRequest.h>
#include <vehicle_manager/EditVehicleResponse.h>


namespace vehicle_manager
{

struct EditVehicle
{

typedef EditVehicleRequest Request;
typedef EditVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EditVehicle
} // namespace vehicle_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vehicle_manager::EditVehicle > {
  static const char* value()
  {
    return "c1e037ffea88992a21a708541cb21c87";
  }

  static const char* value(const ::vehicle_manager::EditVehicle&) { return value(); }
};

template<>
struct DataType< ::vehicle_manager::EditVehicle > {
  static const char* value()
  {
    return "vehicle_manager/EditVehicle";
  }

  static const char* value(const ::vehicle_manager::EditVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::vehicle_manager::EditVehicleRequest> should match
// service_traits::MD5Sum< ::vehicle_manager::EditVehicle >
template<>
struct MD5Sum< ::vehicle_manager::EditVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::EditVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::EditVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::EditVehicleRequest> should match
// service_traits::DataType< ::vehicle_manager::EditVehicle >
template<>
struct DataType< ::vehicle_manager::EditVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::EditVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::EditVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vehicle_manager::EditVehicleResponse> should match
// service_traits::MD5Sum< ::vehicle_manager::EditVehicle >
template<>
struct MD5Sum< ::vehicle_manager::EditVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::EditVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::EditVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::EditVehicleResponse> should match
// service_traits::DataType< ::vehicle_manager::EditVehicle >
template<>
struct DataType< ::vehicle_manager::EditVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::EditVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::EditVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_EDITVEHICLE_H
