// Generated by gencpp from file vehicle_manager/FindVehicleResponse.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_FINDVEHICLERESPONSE_H
#define VEHICLE_MANAGER_MESSAGE_FINDVEHICLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vehicle_manager/Vehicle.h>

namespace vehicle_manager
{
template <class ContainerAllocator>
struct FindVehicleResponse_
{
  typedef FindVehicleResponse_<ContainerAllocator> Type;

  FindVehicleResponse_()
    : success(false)
    , message()
    , vehicle()  {
    }
  FindVehicleResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , vehicle(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::vehicle_manager::Vehicle_<ContainerAllocator>  _vehicle_type;
  _vehicle_type vehicle;





  typedef boost::shared_ptr< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindVehicleResponse_

typedef ::vehicle_manager::FindVehicleResponse_<std::allocator<void> > FindVehicleResponse;

typedef boost::shared_ptr< ::vehicle_manager::FindVehicleResponse > FindVehicleResponsePtr;
typedef boost::shared_ptr< ::vehicle_manager::FindVehicleResponse const> FindVehicleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator1> & lhs, const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.vehicle == rhs.vehicle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator1> & lhs, const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4767fa5567382080303c4affeb8eaf62";
  }

  static const char* value(const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4767fa5567382080ULL;
  static const uint64_t static_value2 = 0x303c4affeb8eaf62ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_manager/FindVehicleResponse";
  }

  static const char* value(const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"Vehicle vehicle\n"
"\n"
"================================================================================\n"
"MSG: vehicle_manager/Vehicle\n"
"string licensePlate\n"
"string make\n"
"string model\n"
"uint32 year\n"
;
  }

  static const char* value(const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.vehicle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindVehicleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_manager::FindVehicleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_manager::FindVehicleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vehicle: ";
    Printer< ::vehicle_manager::Vehicle_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_FINDVEHICLERESPONSE_H
