// Generated by gencpp from file vehicle_manager/FindVehicleRequest.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_FINDVEHICLEREQUEST_H
#define VEHICLE_MANAGER_MESSAGE_FINDVEHICLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_manager
{
template <class ContainerAllocator>
struct FindVehicleRequest_
{
  typedef FindVehicleRequest_<ContainerAllocator> Type;

  FindVehicleRequest_()
    : licensePlate()  {
    }
  FindVehicleRequest_(const ContainerAllocator& _alloc)
    : licensePlate(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _licensePlate_type;
  _licensePlate_type licensePlate;





  typedef boost::shared_ptr< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindVehicleRequest_

typedef ::vehicle_manager::FindVehicleRequest_<std::allocator<void> > FindVehicleRequest;

typedef boost::shared_ptr< ::vehicle_manager::FindVehicleRequest > FindVehicleRequestPtr;
typedef boost::shared_ptr< ::vehicle_manager::FindVehicleRequest const> FindVehicleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator1> & lhs, const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.licensePlate == rhs.licensePlate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator1> & lhs, const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b518cc12125eb37ea279af24b53a577d";
  }

  static const char* value(const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb518cc12125eb37eULL;
  static const uint64_t static_value2 = 0xa279af24b53a577dULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_manager/FindVehicleRequest";
  }

  static const char* value(const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string licensePlate\n"
;
  }

  static const char* value(const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.licensePlate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindVehicleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_manager::FindVehicleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_manager::FindVehicleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "licensePlate: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.licensePlate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_FINDVEHICLEREQUEST_H
