// Generated by gencpp from file vehicle_manager/FindVehicle.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_FINDVEHICLE_H
#define VEHICLE_MANAGER_MESSAGE_FINDVEHICLE_H

#include <ros/service_traits.h>


#include <vehicle_manager/FindVehicleRequest.h>
#include <vehicle_manager/FindVehicleResponse.h>


namespace vehicle_manager
{

struct FindVehicle
{

typedef FindVehicleRequest Request;
typedef FindVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindVehicle
} // namespace vehicle_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vehicle_manager::FindVehicle > {
  static const char* value()
  {
    return "4a85880fc8ab4e0e9fa8688f0b93aaf9";
  }

  static const char* value(const ::vehicle_manager::FindVehicle&) { return value(); }
};

template<>
struct DataType< ::vehicle_manager::FindVehicle > {
  static const char* value()
  {
    return "vehicle_manager/FindVehicle";
  }

  static const char* value(const ::vehicle_manager::FindVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::vehicle_manager::FindVehicleRequest> should match
// service_traits::MD5Sum< ::vehicle_manager::FindVehicle >
template<>
struct MD5Sum< ::vehicle_manager::FindVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::FindVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::FindVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::FindVehicleRequest> should match
// service_traits::DataType< ::vehicle_manager::FindVehicle >
template<>
struct DataType< ::vehicle_manager::FindVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::FindVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::FindVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vehicle_manager::FindVehicleResponse> should match
// service_traits::MD5Sum< ::vehicle_manager::FindVehicle >
template<>
struct MD5Sum< ::vehicle_manager::FindVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::FindVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::FindVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::FindVehicleResponse> should match
// service_traits::DataType< ::vehicle_manager::FindVehicle >
template<>
struct DataType< ::vehicle_manager::FindVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::FindVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::FindVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_FINDVEHICLE_H
