// Generated by gencpp from file vehicle_manager/RegisterVehicle.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLE_H
#define VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLE_H

#include <ros/service_traits.h>


#include <vehicle_manager/RegisterVehicleRequest.h>
#include <vehicle_manager/RegisterVehicleResponse.h>


namespace vehicle_manager
{

struct RegisterVehicle
{

typedef RegisterVehicleRequest Request;
typedef RegisterVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RegisterVehicle
} // namespace vehicle_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vehicle_manager::RegisterVehicle > {
  static const char* value()
  {
    return "00a0a814922db1043c61a97c21d2aa61";
  }

  static const char* value(const ::vehicle_manager::RegisterVehicle&) { return value(); }
};

template<>
struct DataType< ::vehicle_manager::RegisterVehicle > {
  static const char* value()
  {
    return "vehicle_manager/RegisterVehicle";
  }

  static const char* value(const ::vehicle_manager::RegisterVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::vehicle_manager::RegisterVehicleRequest> should match
// service_traits::MD5Sum< ::vehicle_manager::RegisterVehicle >
template<>
struct MD5Sum< ::vehicle_manager::RegisterVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::RegisterVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::RegisterVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::RegisterVehicleRequest> should match
// service_traits::DataType< ::vehicle_manager::RegisterVehicle >
template<>
struct DataType< ::vehicle_manager::RegisterVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::RegisterVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::RegisterVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vehicle_manager::RegisterVehicleResponse> should match
// service_traits::MD5Sum< ::vehicle_manager::RegisterVehicle >
template<>
struct MD5Sum< ::vehicle_manager::RegisterVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vehicle_manager::RegisterVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::RegisterVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vehicle_manager::RegisterVehicleResponse> should match
// service_traits::DataType< ::vehicle_manager::RegisterVehicle >
template<>
struct DataType< ::vehicle_manager::RegisterVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::vehicle_manager::RegisterVehicle >::value();
  }
  static const char* value(const ::vehicle_manager::RegisterVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLE_H
