// Generated by gencpp from file vehicle_manager/RegisterVehicleRequest.msg
// DO NOT EDIT!


#ifndef VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLEREQUEST_H
#define VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vehicle_manager/Vehicle.h>

namespace vehicle_manager
{
template <class ContainerAllocator>
struct RegisterVehicleRequest_
{
  typedef RegisterVehicleRequest_<ContainerAllocator> Type;

  RegisterVehicleRequest_()
    : vehicle()
    , command()  {
    }
  RegisterVehicleRequest_(const ContainerAllocator& _alloc)
    : vehicle(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vehicle_manager::Vehicle_<ContainerAllocator>  _vehicle_type;
  _vehicle_type vehicle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterVehicleRequest_

typedef ::vehicle_manager::RegisterVehicleRequest_<std::allocator<void> > RegisterVehicleRequest;

typedef boost::shared_ptr< ::vehicle_manager::RegisterVehicleRequest > RegisterVehicleRequestPtr;
typedef boost::shared_ptr< ::vehicle_manager::RegisterVehicleRequest const> RegisterVehicleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator1> & lhs, const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vehicle == rhs.vehicle &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator1> & lhs, const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6aafe4c90b6c629dae901be2eb85a1c";
  }

  static const char* value(const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6aafe4c90b6c629ULL;
  static const uint64_t static_value2 = 0xdae901be2eb85a1cULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_manager/RegisterVehicleRequest";
  }

  static const char* value(const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Vehicle vehicle \n"
"string command\n"
"\n"
"================================================================================\n"
"MSG: vehicle_manager/Vehicle\n"
"string licensePlate\n"
"string make\n"
"string model\n"
"uint32 year\n"
;
  }

  static const char* value(const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterVehicleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_manager::RegisterVehicleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vehicle: ";
    Printer< ::vehicle_manager::Vehicle_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MANAGER_MESSAGE_REGISTERVEHICLEREQUEST_H
