(cl:defpackage vehicle_manager-srv
  (:use )
  (:export
   "DISPLAYALLVEHICLE"
   "<DISPLAYALLVEHICLE-REQUEST>"
   "DISPLAYALLVEHICLE-REQUEST"
   "<DISPLAYALLVEHICLE-RESPONSE>"
   "DISPLAYALLVEHICLE-RESPONSE"
   "FINDVEHICLE"
   "<FINDVEHICLE-REQUEST>"
   "FINDVEHICLE-REQUEST"
   "<FINDVEHICLE-RESPONSE>"
   "FINDVEHICLE-RESPONSE"
   "REGISTERVEHICLE"
   "<REGISTERVEHICLE-REQUEST>"
   "REGISTERVEHICLE-REQUEST"
   "<REGISTERVEHICLE-RESPONSE>"
   "REGISTERVEHICLE-RESPONSE"
  ))

